USE `billSoftware`;

INSERT INTO `category_templates` (`category_type`, `name`, `sort_order`) VALUES
('expense', '早午晚餐', 1),
('expense', '餐饮', 2),
('expense', '购物', 3),
('expense', '日用', 4),
('expense', '奶茶', 5),
('expense', '交通', 6),
('expense', '蔬菜', 7),
('expense', '水果', 8),
('expense', '零食', 9),
('expense', '运动', 10),
('expense', '娱乐', 11),
('expense', '通讯', 12),
('expense', '服饰', 13),
('expense', '美容', 14),
('expense', '住房', 15),
('expense', '居家', 16),
('expense', '孩子', 17),
('expense', '长辈', 18),
('expense', '社交', 19),
('expense', '旅行', 20),
('expense', '烟酒', 21),
('expense', '数码', 22),
('expense', '汽车', 23),
('expense', '医疗', 24),
('expense', '学习', 25),
('expense', '宠物', 26),
('expense', '礼物', 27),
('expense', '办公', 28),
('expense', '维修', 29),
('expense', '捐赠', 30),
('expense', '彩票', 31),
('expense', '亲友', 32),
('expense', '快递', 33),
('income', '工资', 1),
('income', '兼职', 2),
('income', '理财', 3),
('income', '礼金', 4),
('income', '其他', 5)
ON DUPLICATE KEY UPDATE
`name` = VALUES(`name`);

